version: '3.8'
services:
  db:
    image: mysql:8.3
    ports:
      - 33060:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d/:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root843874
      MYSQL_DATABASE: deadline
      MYSQL_USER: deadline-app
      MYSQL_PASSWORD: 6aDhk037a2e